### ISSUE TITLE
Sportschau Videos lassen sich nicht abspielen

### ISSUE THREAD

**Issue by sti0** [prof-membrane/plugin.video.wdrmediathek#4]
Betriebssystem: OpenELEC 8.04

Kodi Version: 17.3

Add-on Version: 1.1.0

Bibliothek: libwdr 1.1.0

Wenn ich unter Video Addons -> Sportschau -> Fußball
ein beliebiges Video auswähle kommt es zum Fehler.

Log:
```
11:55:35.346 T:1094710176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.sportschau/default.py", line 89, in <module>
                                                list()
                                              File "/storage/.kodi/addons/plugin.video.sportschau/default.py", line 84, in list
                                                libwdr.list()
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdr.py", line 82, in list
                                                libMediathek.play(libWdrPlay())
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdr.py", line 58, in libWdrPlay
                                                return libWdrParser.parseVideo(params['url'])
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdrparser.py", line 58, in parseVideo
                                                url = re.compile("'mediaObj': { 'url': '(.+?)'", re.DOTALL).findall(response)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
11:55:35.653 T:1946738704   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.sportschau/?sort=130000&url=http%3A%2F%2Fwww.sportschau.de%2Ffussball%2Fbundesliga%2Fvideo-markus-gisdol---den-kleinen-torfluch-brechen-100.html&mode=libWdrPlay]
```

Folgendes muss in "libwdrparser.py" in Zeile 58 geändert werden:

Von:
`url = re.compile("'mediaObj': { 'url': '(.+?)'", re.DOTALL).findall(response)[0]`

Ändern in:
`url = re.compile('"mediaObj":{"url":"(.+?)"', re.DOTALL).findall(response)[0]`

Dann laufen die Sportschau und WDR Videos wieder.

**Comment by prof-membrane** [comment]
Ich hab es etwas anders gelöst.

**Comment by sti0** [comment]
Keine Ursache...
