### ISSUE TITLE
Eigentlich für ZDF Mediathek: defekt, HTTP 403 im Log

### ISSUE THREAD

**Issue by t0mcat1337** [prof-membrane/plugin.video.wdrmediathek#6]
Eigentlich müßte dieser Issue im Bereich des ZDF Mediathek Plugins geschrieben werden, aber dort existiert kein Reiter "Issues" und der Link im Wiki führt zu "Pull Requests". Daher hier der Bug Report:

Betriebssystem: LibreElec 8.1.2
Kodi Version: 17.4
Add-on Version: 4.1.0
`<addon id="plugin.video.zdf_de_lite" name="ZDF Mediathek" version="4.1.0" provider-name="sarbes">
`
Bibliothek: libZdf 2.1.1
```
<addon id="script.module.libzdf"
             name="libzdf"
             version="2.1.1"
             provider-name="sarbes">


```
Bibliothek: libMediathek3 1.4.1
```
<addon id="script.module.libmediathek3" 
             name="libmediathek3" 
             version="1.4.1" 
             provider-name="sarbes">


```

Die ZDF Mediathek funktioniert nicht mehr. Egal, welches Top Level Element dort gewählt wird, erscheint das hier im Log:

```
13:30:19.736 T:140567207986944   ERROR: GetDirectory - Error getting
13:30:22.308 T:140567150290688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 403: Forbidden
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.zdf_de_lite/default.py", line 5, in <module>
                                                libzdf.list()
                                              File "/storage/.kodi/addons/script.module.libzdf/lib/libzdf.py", line 93, in list
                                                l = modes.get(mode,libZdfListMain)()
                                              File "/storage/.kodi/addons/script.module.libzdf/lib/libzdf.py", line 37, in libZdfListShows
                                                return libZdfJsonParser.getAZ()
                                              File "/storage/.kodi/addons/script.module.libzdf/lib/libzdfjsonparser.py", line 40, in getAZ
                                                response = libMediathek.getUrl("https://api.zdf.de/content/documents/sendungen-100.json?profile=default",getheader3)
                                              File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 28, in getUrl
                                                return _request(url,headers,post)
                                              File "/storage/.kodi/addons/script.module.libmediathek3/lib/libmediathek3utils.py", line 52, in _request
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                              File "/usr/lib/python2.7/urllib2.py", line 435, in open
                                              File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
                                              File "/usr/lib/python2.7/urllib2.py", line 473, in error
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                              File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
                                            HTTPError: HTTP Error 403: Forbidden
                                            -->End of Python script error report<--

```

Ich schätze, das hat mit nicht korrekten API Keys zu tun. Da ich gesehen habe, dass es gestern eine Aktualisierung in der libZdf betreffend der Keys gab, habe ich (um sicher zu gehen), sowohl die ZIP der libZdf als auch vom plugin.video.zdf_de_lite direkt hier von Github heruntergeladen und installiert. Das Ergebnis bleibt jedoch identisch.

**Comment by prof-membrane** [comment]
Ich hab den Issue-Tracker wieder aufgemacht. Außerdem habe ich eine neue Version hochgeladen.
