### ISSUE TITLE
WDR Rockpalast wirft Fehler

### ISSUE THREAD

**Issue by b-jesch** [prof-membrane/plugin.video.wdrmediathek#8]
Das Addon WDR Rockpalast wirft einen Fehler. Videos (egal welche) können nicht abgespielt werden. Der Fehler wird [hier](https://www.kodinerds.net/index.php/Thread/51258-WDR-Rockpalast-k%C3%B6nnte-es-jemand-weiterf%C3%BChren/?postID=435232#post435232) beschrieben, hier nochmal der entsprechende Fehlercode:

```
10:19:18.368 T:139924226803456    INFO: initializing python engine.
10:19:18.368 T:139924226803456   DEBUG: CPythonInvoker(40, /storage/.kodi/addons/plugin.video.wdrrockpalast/default.py): start processing
10:19:18.371 T:139926361827072   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
10:19:18.371 T:139926361827072   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
10:19:18.377 T:139925215975168   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"title":"Rockpalast: Beatsteaks - Köln, E-Werk 2017","type":"video","year":2017},"playlistid":1,"position":0}
10:19:18.382 T:139924226803456   DEBUG: -->Python Interpreter Initialized<--
10:19:18.382 T:139924226803456   DEBUG: CPythonInvoker(40, /storage/.kodi/addons/plugin.video.wdrrockpalast/default.py): the source file to load is "/storage/.kodi/addons/plugin.video.wdrrockpalast/default.py"
10:19:18.382 T:139924226803456   DEBUG: CPythonInvoker(40, /storage/.kodi/addons/plugin.video.wdrrockpalast/default.py): setting the Python path to /storage/.kodi/addons/plugin.video.wdrrockpalast:/storage/.kodi/addons/script.module.libmediathek3/lib:/storage/.kodi/addons/script.module.libwdr/lib:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/gtk-2.0
10:19:18.382 T:139924226803456   DEBUG: CPythonInvoker(40, /storage/.kodi/addons/plugin.video.wdrrockpalast/default.py): entering source directory /storage/.kodi/addons/plugin.video.wdrrockpalast
10:19:18.382 T:139924226803456   DEBUG: CPythonInvoker(40, /storage/.kodi/addons/plugin.video.wdrrockpalast/default.py): instantiating addon using automatically obtained id of "plugin.video.wdrrockpalast" dependent on version 2.25.0 of the xbmc.python api
10:19:18.388 T:139924498003712   DEBUG: Thread scriptobs start, auto delete: false
10:19:18.433 T:139924226803456   DEBUG: http://www1.wdr.de/mediathek/video/sendungen/rockpalast/video-rockpalast-beatsteaks---koeln-e-werk--100.html
10:19:18.462 T:139924867118848   DEBUG: Previous line repeats 1 times.
10:19:18.462 T:139924867118848   DEBUG: Skin Helper Widgets --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"title":"Rockpalast: Beatsteaks - Köln, E-Werk 2017","type":"video","year":2017},"playlistid":1,"position":0}
10:19:18.588 T:139926428951488   DEBUG: ------ Window Init (DialogBusy.xml) ------
10:19:18.645 T:139924226803456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Extra data: line 1 column 76 - line 20 column 63 (char 75 - 1414)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.wdrrockpalast/default.py", line 42, in <module>
                                                list()
                                              File "/storage/.kodi/addons/plugin.video.wdrrockpalast/default.py", line 32, in list
                                                libWdr.list()
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdr.py", line 82, in list
                                                libMediathek.play(libWdrPlay())
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdr.py", line 58, in libWdrPlay
                                                return libWdrParser.parseVideo(params['url'])
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdrparser.py", line 57, in parseVideo
                                                j = json.loads(re.compile('<a href="javascript:void\(0\);" class="mediaLink video" data-extension=\'(.+?)\'>', re.DOTALL).findall(response)[0])
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
                                            ValueError: Extra data: line 1 column 76 - line 20 column 63 (char 75 - 1414)
                                            -->End of Python script error report<--
10:19:18.650 T:139924226803456    INFO: Python script stopped
```
Libreelec Milhouse 9
Kodi 18 Leia

**Comment by prof-membrane** [comment]
Ist in meinem Repo gefixt.

**Comment by b-jesch** [comment]
Nein, ist es nicht.
Ich vergaß zu erwähnen:

plugin.video.rockpalast 1.1.0
aus dem Repo: repository.membrane 1.9.0

Hier die Fehlermeldung unter Kodi 17.6 (Ubuntu 14.04), die quasi identisch zum ersten Bugreport ist.:
```
15:47:43.743 T:139879832668224   DEBUG: OnPlayMedia plugin://plugin.video.wdrrockpalast/?sort=000000&url=http%3A%2F%2Fwww1.wdr.de%2Fmediathek%2Fvideo%2Fsendungen%2Frockpalast%2Fvideo-rockpalast-zz-top---grugahalle-essen-100.html&mode=libWdrPlay
15:47:43.744 T:139879373592320   DEBUG: CAnnouncementManager - Announcement: OnClear from xbmc
15:47:43.744 T:139879373592320   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnClear
15:47:43.747 T:139879373592320   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc
15:47:43.747 T:139879373592320   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd
15:47:43.748 T:139879832668224   DEBUG: StartScript - calling plugin WDR Rockpalast('plugin://plugin.video.wdrrockpalast/','16','?sort=000000&url=http%3A%2F%2Fwww1.wdr.de%2Fmediathek%2Fvideo%2Fsendungen%2Frockpalast%2Fvideo-rockpalast-zz-top---grugahalle-essen-100.html&mode=libWdrPlay')
15:47:43.748 T:139878117385984   DEBUG: Thread LanguageInvoker start, auto delete: false
15:47:43.748 T:139878117385984    INFO: initializing python engine.
15:47:43.748 T:139878117385984   DEBUG: CPythonInvoker(35, /home/kodi/.kodi/addons/plugin.video.wdrrockpalast/default.py): start processing
15:47:43.768 T:139877773543168   DEBUG: Thread scriptobs start, auto delete: false
15:47:43.804 T:139878117385984   DEBUG: -->Python Interpreter Initialized<--
15:47:43.804 T:139878117385984   DEBUG: CPythonInvoker(35, /home/kodi/.kodi/addons/plugin.video.wdrrockpalast/default.py): the source file to load is "/home/kodi/.kodi/addons/plugin.video.wdrrockpalast/default.py"
15:47:43.804 T:139878117385984   DEBUG: CPythonInvoker(35, /home/kodi/.kodi/addons/plugin.video.wdrrockpalast/default.py): setting the Python path to /home/kodi/.kodi/addons/plugin.video.wdrrockpalast:/home/kodi/.kodi/addons/script.module.libmediathek3/lib:/home/kodi/.kodi/addons/script.module.libwdr/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0
15:47:43.804 T:139878117385984   DEBUG: CPythonInvoker(35, /home/kodi/.kodi/addons/plugin.video.wdrrockpalast/default.py): entering source directory /home/kodi/.kodi/addons/plugin.video.wdrrockpalast
15:47:43.804 T:139878117385984   DEBUG: CPythonInvoker(35, /home/kodi/.kodi/addons/plugin.video.wdrrockpalast/default.py): instantiating addon using automatically obtained id of "plugin.video.wdrrockpalast" dependent on version 2.25.0 of the xbmc.python api
15:47:43.821 T:139878576469760   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnClear  - data: {"playlistid":1}
15:47:43.821 T:139878576469760   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Playlist.OnAdd  - data: {"item":{"title":"Rockpalast: ZZ Top - Grugahalle, Essen","type":"video","year":2017},"playlistid":1,"position":0}
15:47:43.935 T:139878117385984   DEBUG: http://www1.wdr.de/mediathek/video/sendungen/rockpalast/video-rockpalast-zz-top---grugahalle-essen-100.html
15:47:43.968 T:139879832668224   DEBUG: Previous line repeats 1 times.
15:47:43.968 T:139879832668224   DEBUG: ------ Window Init (DialogBusy.xml) ------
15:47:44.103 T:139878117385984   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Extra data: line 1 column 76 - line 20 column 63 (char 75 - 1268)
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.wdrrockpalast/default.py", line 42, in <module>
                                                list()
                                              File "/home/kodi/.kodi/addons/plugin.video.wdrrockpalast/default.py", line 32, in list
                                                libWdr.list()
                                              File "/home/kodi/.kodi/addons/script.module.libwdr/lib/libwdr.py", line 82, in list
                                                libMediathek.play(libWdrPlay())
                                              File "/home/kodi/.kodi/addons/script.module.libwdr/lib/libwdr.py", line 58, in libWdrPlay
                                                return libWdrParser.parseVideo(params['url'])
                                              File "/home/kodi/.kodi/addons/script.module.libwdr/lib/libwdrparser.py", line 57, in parseVideo
                                                j = json.loads(re.compile('<a href="javascript:void\(0\);" class="mediaLink video" data-extension=\'(.+?)\'>', re.DOTALL).findall(response)[0])
                                              File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 369, in decode
                                                raise ValueError(errmsg("Extra data", s, end, len(s)))
                                            ValueError: Extra data: line 1 column 76 - line 20 column 63 (char 75 - 1268)
                                            -->End of Python script error report<--
15:47:44.105 T:139878117385984    INFO: Python script stopped
```

**Comment by prof-membrane** [comment]
Repo Inhalt aktualisieren! Der Fehler ist bereinigt.
