### ISSUE TITLE
Fehler beim Abspielen 

### ISSUE THREAD

**Issue by raxon91** [prof-membrane/plugin.video.wdrmediathek#9]
Hallo, 

ich habe heute das Addon installiert, aber es kommt bei jedem Video ein Fehler beim Abspielen. 

Ich habe die neuste Version des Addons und von Abhängigkeiten aus deiner Repo (github) runtergeladen.

**Comment by timoon** [comment]
Same here, no playback.
kodi.log:

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.wdrmediathek/default.py", line 4, in <module>
                                                libwdr.list()
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdr.py", line 83, in list
                                                libMediathek.play(libWdrPlay())
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdr.py", line 61, in libWdrPlay
                                                return libWdrParser.parseVideo(params['url'])
                                              File "/storage/.kodi/addons/script.module.libwdr/lib/libwdrparser.py", line 57, in parseVideo
                                                url2 = re.compile("'mediaObj': { 'url': '(.+?)'", re.DOTALL).findall(response)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--


ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.wdrmediathek/?sort=080000&url=https%3A%2F%2Fwww1.wdr.de%2Fmediathek%2Fvideo%2Fsendungen%2Fwunderschoen
%2Fvideo-wunderschoen-urlaub-in-nordholland-102.html&mode=libWdrPlay]

```

**Comment by Collabsvito** [comment]
@timoon 

Ich erlaube mir mal kurzfristig für den Ersteller der in dieser REPO gelisteten Addons zu antworten:
Sorry, aber Du hast noch eine alte Version der "script.module.libwdr" installiert.
Bitte updaten auf die aktuelle Version 1.1.3 - dann läuft wieder alles !

Gruß

**Comment by timoon** [comment]
@Collabsvito 

Sorry ich kenn mich leider nicht gut mit github aus. Wenn ich das richtig sehe, muss der Autor einen pull request an das kodi.tv repo stellen?
Denn dort gibt es nur script.module.libwdr-1.0.0

**Comment by Collabsvito** [comment]
@timoon 

Nimm doch erstmal die funktionierende Version hier aus der Repo, die Aktualisierungen in der offiziellen "kodi.tv" repo können Wochen dauern, wegen der vielen Vorschriften die man beachten muss !
Gruß

**Comment by timoon** [comment]
@Collabsvito 

Ja funktioniert super, wir haben es schon im Einsatz, danke!
